import os
import subprocess
from langchain.tools import tool
from .utiles import resolve_virtual_path
from optclaw.log import setup_logging

logger = setup_logging(__name__)

_DEFAULT_TIMEOUT = 30  # 默认脚本执行超时时间（秒）
_MAX_OUTPUT_BYTES = 50 * 1024  # 限制返回给大语言模型的最大输出大小（约 50KB），防止 context 撑爆


@tool("execute_python", parse_docstring=True)
def execute_python_file_tool(path: str, args: list = None, timeout: int = _DEFAULT_TIMEOUT) -> str:
    """Execute a specific Python file with optional arguments and return its standard output and error.
    Use this to run local scripts, automation tasks, or data processing files.

    When to use the execute_python_file tool:
    - Use this when you need to run an existing Python script or pipeline.
    - Use this to get the calculation or execution results generated by a script.
    - Pass command-line arguments to the Python script via the args parameter.

    Args:
        path: The absolute path of the Python file to execute.
        args: Optional list of command-line arguments to pass to the Python script. Defaults to None.
        timeout: The maximum execution time in seconds. Defaults to 30.
    """
    # 1. 解析虚拟路径（保持安全逻辑一致）
    actual_path = resolve_virtual_path(path)

    if not actual_path:
        raise ValueError(f"Path: {path} resolve to None, access denied for security reasons! Please use absolute path.") from None

    actual_path = str(actual_path)

    # 2. 参数校验与限制
    if timeout <= 0:
        return "Error: Timeout must be greater than 0 seconds."

    try:
        # 3. 检查文件合法性
        if not os.path.exists(actual_path):
            return f"Error: File not found: {path}"
        if os.path.isdir(actual_path):
            return f"Error: Path is a directory, cannot execute: {path}"
        if not actual_path.endswith('.py'):
            return f"Error: Target is not a Python (.py) file: {path}"

        display_name = os.path.basename(actual_path)

        # 4. 安全、隔离地执行 Python 文件
        import sys
        python_executable = sys.executable
        
        # 构建执行命令：解释器 + 文件路径 + 可选参数
        command = [python_executable, actual_path]
        if args and isinstance(args, list):
            command.extend(args)

        result = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            encoding='utf-8',
            errors='replace',
            timeout=timeout
        )

        # 5. 组装输出结果
        output_segments = [f"Execution of '{display_name}' finished with exit code {result.returncode}."]
        
        if result.stdout:
            output_segments.append("\n--- Standard Output ---")
            output_segments.append(result.stdout)
            
        if result.stderr:
            output_segments.append("\n--- Standard Error ---")
            output_segments.append(result.stderr)

        full_output = "\n".join(output_segments)

        # 6. 大语言模型上下文保护：如果输出过大，进行截断
        if len(full_output.encode('utf-8')) > _MAX_OUTPUT_BYTES:
            logger.warning(f"Execution output of {display_name} exceeded maximum allowed bytes. Truncating.")
            truncated_hint = "\n\n[Warning: Output was truncated because it exceeded the maximum context limit.]"
            return full_output[:_MAX_OUTPUT_BYTES] + truncated_hint

        return full_output

    except subprocess.TimeoutExpired:
        logger.error(f"Execution of {path} timed out after {timeout} seconds.")
        return "Error: Execution timed out after {timeout} seconds. The process was terminated."
    except OSError as e:
        raise type(e)(e.errno, e.strerror, path) from None